// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> compress({
  required String sourceFolderPath,
  required String outputZipPath,
  required CompressionMethod compressionMethod,
}) => RustLib.instance.api.crateApiCompressCompress(
  sourceFolderPath: sourceFolderPath,
  outputZipPath: outputZipPath,
  compressionMethod: compressionMethod,
);

Future<void> decompress({
  required String sourceZipPath,
  required String outputFolderPath,
}) => RustLib.instance.api.crateApiCompressDecompress(
  sourceZipPath: sourceZipPath,
  outputFolderPath: outputFolderPath,
);

Future<Zipper> createZipper({
  required String zipPath,
  required CompressionMethod compressionMethod,
}) => RustLib.instance.api.crateApiCompressCreateZipper(
  zipPath: zipPath,
  compressionMethod: compressionMethod,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Zipper>>
abstract class Zipper implements RustOpaqueInterface {
  /// 添加整个目录（递归，所有文件都会被加入）
  Future<void> addDirectory({required String dirPath});

  Future<void> addEmptyDirectory({required String dirName});

  /// 添加单个文件（会自动保留相对路径结构）
  Future<void> addFile({required String filePath, String? pathInZip});

  Future<void> close();
}

enum CompressionMethod {
  stored,
  deflated,
  deflate64,
  bzip2,
  aes,
  zstd,
  lzma,
  xz,
  ppmd,
}
