// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> compress({
  required String sourceFolderPath,
  required String outputZipPath,
  required CompressionMethod compressionMethod,
}) => RustLib.instance.api.crateApiSimpleCompress(
  sourceFolderPath: sourceFolderPath,
  outputZipPath: outputZipPath,
  compressionMethod: compressionMethod,
);

Future<void> decompress({
  required String sourceZipPath,
  required String outputFolderPath,
}) => RustLib.instance.api.crateApiSimpleDecompress(
  sourceZipPath: sourceZipPath,
  outputFolderPath: outputFolderPath,
);

enum CompressionMethod {
  stored,
  deflated,
  deflate64,
  bzip2,
  aes,
  zstd,
  lzma,
  xz,
  ppmd,
}
