// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `create_headers_at`, `get_signature`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<HeaderMap>>
abstract class HeaderMap implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<InvalidHeaderValue>>
abstract class InvalidHeaderValue implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Method>>
abstract class Method implements RustOpaqueInterface {}

class Client {
  final String token;

  const Client({required this.token});

  static Future<HeaderMap> createHeaders({
    required String url,
    required Method method,
    required String authorization,
    required String imageQuality,
  }) => RustLib.instance.api.crateApiDownloadClientClientCreateHeaders(
    url: url,
    method: method,
    authorization: authorization,
    imageQuality: imageQuality,
  );

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<Client> newInstance({required String token}) =>
      RustLib.instance.api.crateApiDownloadClientClientNew(token: token);

  @override
  int get hashCode => token.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Client &&
          runtimeType == other.runtimeType &&
          token == other.token;
}
